/** Cover images live in this Netlify Blobs store. */
export const MEDIA_STORE = "news-media";

export const MAX_UPLOAD_BYTES = 5 * 1024 * 1024;

/**
 * Image types accepted for cover uploads, mapped to the file extension used in
 * the blob key. The extension is how the serving function recovers the
 * content type, so nothing outside this list can be stored.
 */
export const ALLOWED_IMAGE_TYPES: Record<string, string> = {
  "image/jpeg": "jpg",
  "image/png": "png",
  "image/webp": "webp",
  "image/gif": "gif",
  "image/avif": "avif",
};

const EXTENSION_TO_TYPE: Record<string, string> = {
  jpg: "image/jpeg",
  png: "image/png",
  webp: "image/webp",
  gif: "image/gif",
  avif: "image/avif",
};

export function contentTypeForKey(key: string): string | null {
  const extension = key.split(".").pop();
  if (!extension) {
    return null;
  }
  return EXTENSION_TO_TYPE[extension.toLowerCase()] ?? null;
}

/** Keys are generated by this app, so anything else is rejected on read. */
export function isValidMediaKey(key: string): boolean {
  return /^[a-z0-9]+-[a-z0-9]+\.(jpg|png|webp|gif|avif)$/.test(key);
}

export function buildMediaKey(extension: string): string {
  const stamp = Date.now().toString(36);
  const random = Math.random().toString(36).slice(2, 10);
  return `${stamp}-${random}.${extension}`;
}
